import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='py-4 px-6'>
        <header>
          <nav className='flex items-center justify-between'>
            <p className='text-xl'>kchng.org</p>
            <img className='w-6' src="/hamburger.svg" alt="" />
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}

